[package]
name = "decoder"
version = "0.1.0"
authors = ["ssfdust <ssfdust@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
